version: 0.1
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run pkg
  post_build:
    commands:
      - npm run pub
artifacts:
  type: zip
  files:
    - serverless-output.yaml
