---
pipeline:
  roleArn: arn:aws:iam::163859100295:role/AWS-CodePipeline-Service
  stages:
  - name: Source
    actions:
    - inputArtifacts: []
      name: Source
      actionTypeId:
        category: Source
        owner: ThirdParty
        version: '1'
        provider: GitHub
      outputArtifacts:
      - name: MyApp
      configuration:
        Owner: justengland
        Repo: aws-serverless
        Branch: master
        OAuthToken: "****"
      runOrder: 1
  - name: Build
    actions:
    - inputArtifacts:
      - name: MyApp
      name: CodeBuild
      actionTypeId:
        category: Build
        owner: AWS
        version: '1'
        provider: CodeBuild
      outputArtifacts:
      - name: MyAppBuild
      configuration:
        ProjectName: Phantom
      runOrder: 1
  - name: Beta
    actions:
    - inputArtifacts:
      - name: MyAppBuild
      name: phantom
      actionTypeId:
        category: Deploy
        owner: AWS
        version: '1'
        provider: CloudFormation
      outputArtifacts: []
      configuration:
        ActionMode: CHANGE_SET_REPLACE
        ChangeSetName: MyChangeset
        RoleArn: arn:aws:iam::163859100295:role/cloudformation-lambda-execution-role
        Capabilities: CAPABILITY_IAM
        StackName: phantom
        TemplatePath: MyAppBuild::serverless-output.yaml
      runOrder: 1
  artifactStore:
    type: S3
    location: codepipeline-us-west-2-198795324424
  name: phantom
  version: 2
