AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SweetLambda:
    Properties:
      CodeUri: s3://lambda-build-store/aws-serverless/18b5fc4adbb62e6b9676e8914901d608
      Description: Some sweet lambda action
      Handler: index.handler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
