AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation CloudWatch Log Janitor Demo Stack
Resources:
  PhantomExecutionPolicy:
    DependsOn:
    - PhantomExecutionRole
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - logs:*
          Effect: Allow
          Resource:
          - arn:aws:logs:*:*:*
        - Action:
          - ec2:Describe*
          - ec2:CreateSnapshot
          - ec2:DeleteSnapshot
          - ec2:CreateTags
          - ec2:ModifySnapshotAttribute
          - ec2:ResetSnapshotAttribute
          Effect: Allow
          Resource:
          - '*'
        Version: '2012-10-17'
      PolicyName: MyLambdaToMakeLogsRolePolicy
      Roles:
      - Ref: PhantomExecutionRole
    Type: AWS::IAM::Policy
  PhantomExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
    Type: AWS::IAM::Role
  PhantomFunction:
    DependsOn:
    - PhantomExecutionRole
    - PhantomExecutionPolicy
    Properties:
      Code:
        S3Bucket: lambda-build-store
        S3Key: phantom/code.zip
      FunctionName: phantom
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - PhantomExecutionRole
        - Arn
      Runtime: nodejs4.3
      Timeout: 60
    Type: AWS::Lambda::Function
