AWSTemplateFormatVersion: '2010-09-09'
Description: Pipeline CFN
Resources:
  Security:
    Properties:
      Parameters:
        EnvironmentName:
          Ref: AWS::StackName
      TemplateURL: s3://lambda-build-store/aws-serverless/af7a79dcebfed6c2abef9a1044b810c7.template
    Type: AWS::CloudFormation::Stack
Transform: AWS::Serverless-2016-10-31
