AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: First working Lambda Pipeline

Resources:

    SweetLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs4.3
            Description: Some sweet lambda action
            CodeUri: .
            # Role: !Ref LambdaExecutionRole

    SweetLambdaBuild:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - codebuild.amazonaws.com
                - codepipeline.amazonaws.com
              Action:
              - sts:AssumeRole
          Path: "/"

    SweetLambdaBuildPolicy:
        Type: AWS::IAM::Policy
        Properties:
          PolicyName: SweetLambdaPipelinePolicy
          Roles:
          - Ref: SweetLambdaPipelineRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - codebuild:*
              - iam:PassRole
              - iam:GetRole
              - iam:CreateRole
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:DeleteRole
              - lambda:*
              - cloudformation:*
              - s3:*
              Resource:
              - "*"