AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pipeline CFN


Resources:
    Security:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: './security.yaml'
            Parameters:
                EnvironmentName: !Ref AWS::StackName